#!/usr/bin/env bash

_github_scripts_init() {
  return 0
}

github_token() {
  meta_check "pass"

  pass_get "dev/github" "token"
}

github_http_init() {
  meta_check "var" "http"

  http_init_client --header "Authorization: Bearer $(github_token)" --header "Accept: application/vnd.github+json" --header "X-GitHub-Api-Version: 2022-11-28"
}
