#!/usr/bin/env bash

script_dir() {
  local FILE_SOURCE="${BASH_SOURCE[0]}"

  if [[ -L ${FILE_SOURCE} ]]; then
    dirname "$(readlink "${FILE_SOURCE}")"
  else
    (
      cd "$(dirname "${FILE_SOURCE}")" && pwd
    )
  fi
}

META_SCRIPT_DIR="$(script_dir)"

meta_check() {
  if [[ ${#} -lt 1 ]]; then
    printf "Usage: meta_check DEPENDENCY_FILENAMES...\n"
    return 1
  fi

  for dep in "${@}"; do
    if [[ $(type -t "_${dep}_scripts_init") != "function" ]]; then
      meta_init "${dep}"
    fi
  done
}

meta_download_script() {
  if [[ ${#} -ne 2 ]]; then
    printf "Usage: meta_download_script LOCAL_NAME REMOTE_NAME\n"
    return 1
  fi

  local LOCAL_NAME="${1}"
  shift

  local REMOTE_NAME="${1}"
  shift

  mkdir -p "$(dirname "${LOCAL_NAME}")"
  curl --disable --silent --show-error --location --max-time 30 --output "${LOCAL_NAME}" -- "${REMOTE_DEPENDENCIES_URL}/${REMOTE_NAME}"
}

meta_init() {
  local REMOTE_DEPENDENCIES_URL="https://raw.githubusercontent.com/ViBiOh/scripts/main/"

  local DIR_BEFORE_INIT="${PWD}"
  cd "${META_SCRIPT_DIR}" || return 1

  for dep in "${@}"; do
    if [[ -z ${dep-} ]]; then
      continue
    fi

    local DEPENDENCY_NAME

    if [[ ${dep} =~ .sh$ ]]; then
      DEPENDENCY_NAME="executables/${DEPENDENCY_NAME}"
    elif ! [[ ${dep} =~ ^hooks/ ]]; then
      DEPENDENCY_NAME="functions/${DEPENDENCY_NAME}"
    fi

    if ! [[ -e "./${dep}" ]]; then
      printf 1>&2 "Downloading script %s...\n" "${DEPENDENCY_NAME}"
      meta_download_script "${dep}" "${DEPENDENCY_NAME}"
    fi

    if [[ ${DEPENDENCY_NAME} =~ ^functions/ ]]; then
      source "./${dep}"

      if [[ $(grep -c "_${dep}_scripts_init" "./${dep}") -eq 1 ]]; then
        "_${dep}_scripts_init"
      fi
    fi

    if [[ ${DEPENDENCY_NAME} =~ ^executables/ ]]; then
      chmod +x "${dep}"
    fi

    if [[ ${DEPENDENCY_NAME} =~ ^hooks/ ]]; then
      chmod +x "${dep}"
    fi
  done

  cd "${DIR_BEFORE_INIT}" >/dev/null || return 1
}
