#!/usr/bin/env bash

_pass_scripts_init() {
  return 0
}

pass_get() {
  if [[ ${#} -lt 2 ]]; then
    var_red "Usage: passget PASS_NAME PASS_FIELD"
    return 1
  fi

  local PASS_NAME="${1}"
  shift

  local PASS_FIELD="${1}"
  shift

  if command -v op >/dev/null 2>&1 && [[ ${PASS_NAME} =~ ^[^\/]*$ ]] && op item get --vault Private "${PASS_NAME}" --field "${PASS_FIELD}" >/dev/null 2>&1; then
    op item get --vault Private "${PASS_NAME}" --field "${PASS_FIELD}" --reveal

    return
  fi

  if command -v pass >/dev/null 2>&1 && [[ -e "${PASSWORD_STORE_DIR:-${HOME}/.password-store}/${PASS_NAME}.gpg" ]]; then
    if [[ ${PASS_FIELD} == "password" ]]; then
      pass show "${PASS_NAME}" | awk 'NR==1 {printf("%s", $1)}'
    else
      pass show "${PASS_NAME}" | awk -v "field=${PASS_FIELD}" -F': ' '$1 == field {printf("%s", $2)}'
    fi

    return
  fi

  var_red "No password manager found"
  return 1
}
