#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

main() {
  local REMOTE_DEPENDENCIES_URL="https://raw.githubusercontent.com/ViBiOh/scripts/main/"
  local SCRIPTS_PATH="./scripts"

  printf "Bootstrapping to %s\n" "${SCRIPTS_PATH}"
  rm -rf "${SCRIPTS_PATH:?}"
  mkdir -p "${SCRIPTS_PATH}"

  (
    cd "${SCRIPTS_PATH}"

    curl --disable --silent --show-error --location --max-time 30 --output "./meta" -- "${REMOTE_DEPENDENCIES_URL}/meta"
    chmod +x "./meta"
    source "./meta" && meta_init "${@}"
  )
}

main "${@}"
