#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

main() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  source "${SCRIPT_DIR}/meta" && meta_init "var" "http"
  var_color

  if [[ ${#} -ne 2 ]]; then
    var_error "Usage: ${0} APP_NAME COMPOSE_FILE"
    return 1
  fi

  local APP_NAME="${1}"
  shift
  local COMPOSE_FILE="${1}"
  shift

  var_read DEPLOY_URL
  var_read DEPLOY_CREDENTIALS

  http_init_client
  http_request --max-time 90 --request POST -u "${DEPLOY_CREDENTIALS}" "${DEPLOY_URL}/${APP_NAME}/" --data-binary "${COMPOSE_FILE}"

  cat "${HTTP_OUTPUT}" 1>&2 && rm "${HTTP_OUTPUT}"
  if [[ ${HTTP_STATUS} != "200" ]]; then
    http_handle_error "Unable to deploy"
    return 1
  fi
}

main "${@:-}"
