#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

main() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  source "${SCRIPT_DIR}/meta" && meta_init "var"
  var_color

  if [[ ${#} -ne 2 ]]; then
    printf "%bUsage: ${0} [APP_NAME] [COMPOSE_FILE]%b\n" "${RED}" "${RESET}"
    return 1
  fi

  var_read DEPLOY_URL
  var_read DEPLOY_CREDENTIALS

  local HTTP_OUTPUT="http_output.txt"
  local HTTP_STATUS

  HTTP_STATUS=$(curl -q -sSL --max-time 90 -X POST -u "${DEPLOY_CREDENTIALS}" -o "${HTTP_OUTPUT}" -w "%{http_code}" "${DEPLOY_URL}/${1}/" --data-binary "${2}")

  cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
  if [[ ${HTTP_STATUS} != "200" ]]; then
    printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}"
    exit 1
  fi
}

main "${@:-}"
