#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

if [[ ${TRACE:-0} == "1" ]]; then
  set -o xtrace
fi

script_dir() {
  local FILE_SOURCE="${BASH_SOURCE[0]}"

  if [[ -L ${FILE_SOURCE} ]]; then
    dirname "$(readlink "${FILE_SOURCE}")"
  else
    (
      cd "$(dirname "${FILE_SOURCE}")" && pwd
    )
  fi
}

main() {
  source "$(script_dir)/meta" && meta_check "var" "pass"

  var_read DOCKER_OWNER "${1-}"
  var_read DOCKER_USER "$(pass_get "dev/docker" "login")"
  var_read DOCKER_PASSWORD "$(pass show "dev/docker" | head -1)" "secret"

  for repo in $(registry-cleaner -username "${DOCKER_USER}" -password "${DOCKER_PASSWORD}" -owner "${DOCKER_OWNER}" -list); do
    registry-cleaner -username "${DOCKER_USER}" -password "${DOCKER_PASSWORD}" -image "${repo}" -delete -grep '^[a-f0-9]{7}($|-)'
    registry-cleaner -username "${DOCKER_USER}" -password "${DOCKER_PASSWORD}" -image "${repo}" -delete -grep '[0-9]{12}' -last
  done

  unset DOCKER_PASSWORD
}

main "${@}"
