#!/usr/bin/env bash

export USE_GKE_GCLOUD_AUTH_PLUGIN=True
export GOOGLE_CONTAINER_REGISTRIES=("gcr.io" "eu.gcr.io" "us.gcr.io")

gcloud_auth() {
  gcloud auth login --update-adc
  gcloud config unset compute/region
  gcloud config set project "$(gcloud projects list | grep dev | awk '{print $1}')"

  if command -v docker >/dev/null 2>&1; then
    for registry in "${GOOGLE_CONTAINER_REGISTRIES[@]}"; do
      gcloud --quiet auth configure-docker "${registry}"
    done
  fi
}

gcloud_docker_login() {
  for registry in "${GOOGLE_CONTAINER_REGISTRIES[@]}"; do
    gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin "https://${registry}"
  done
}

gcloud_project() {
  local GCLOUD_PROJECT
  GCLOUD_PROJECT="$(gcloud projects list --format 'value(projectId)' | fzf --height=20 --ansi --reverse --select-1 --query="${1:-}")"

  if [[ -n ${GCLOUD_PROJECT} ]]; then
    gcloud config set project "${GCLOUD_PROJECT}"
  fi
}

gcloud_kube_import() {
  local CLUSTER_NAME

  IFS='@' read -r -a CLUSTER_NAME <<<"$(gcloud container clusters list --format json | jq --raw-output '.[] | .name + "@" + .zone' | fzf --height=20 --ansi --reverse --select-1 --query="${1:-}")"

  if [[ -n ${CLUSTER_NAME[0]} ]]; then
    gcloud container clusters get-credentials "${CLUSTER_NAME[0]}" --zone "${CLUSTER_NAME[1]}"
    kubectl config rename-context "$(kubectl config current-context)" "$(gcloud config get project 2>/dev/null)_${CLUSTER_NAME[0]}"

    if [[ -n ${2:-} ]]; then
      kubectl config set-context --current --namespace "${2}"
    fi
  fi
}

gcloud_sql_proxy() {
  local SQL_NAME

  IFS='@' read -r -a SQL_NAME <<<"$(gcloud sql instances list --format json | jq --raw-output '.[] | .name + "@" + .connectionName + "@" + .databaseVersion' | fzf --height=20 --ansi --reverse --select-1 --query="${1:-}")"

  if [[ -n ${SQL_NAME[1]} ]]; then
    local SERVICE_ACCOUNT
    SERVICE_ACCOUNT="$(gcloud iam service-accounts list --format json | jq --raw-output '.[] | select(.disabled == false) | .email' | fzf --height=20 --ansi --reverse --select-1 --query="${2:-}")"

    var_info "Connect using: pgcli -h localhost -p '${3:-5432}' -U '${SERVICE_ACCOUNT%.gserviceaccount.com}' <db_name>\n"
    cloud_sql_proxy "-instances=${SQL_NAME[1]}=tcp:127.0.0.1:${3:-5432}" -enable_iam_login -token "$(gcloud auth print-access-token --impersonate-service-account "${SERVICE_ACCOUNT}")"
  fi
}
