#!/usr/bin/env bash

set -o nounset -o errexit

main() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  source "${SCRIPT_DIR}/meta" && meta_init "var" "git"
  var_color

  local BASE="${1:-master}"
  local HEAD="${2:-$(git rev-parse --abbrev-ref HEAD)}"

  local UNCLEAR="false"

  for commit in $(git log --pretty=format:'%s' "${BASE}..${HEAD}"); do
    if [[ $(git_is_commit_wip "${commit}") == "true" ]]; then
      printf "%s %bis a wip commit, please rebase%b\n" "${commit}" "${RED}" "${RESET}"
      UNCLEAR="true"
      continue
    fi

    if [[ $(git_is_conventional_commit "${commit}") != "true" ]]; then
      printf "%s %bis not a conventional commit, please reword%b\n" "${commit}" "${RED}" "${RESET}"
      UNCLEAR="true"
      continue
    fi

    if [[ $(git_is_valid_description "${FIRST_LINE}") != "true" ]]; then
      printf "%s %bis too long, please reword%b\n" "${commit}" "${RED}" "${RESET}"
      UNCLEAR="true"
      continue
    fi
  done

  if [[ ${UNCLEAR} == "true" ]]; then
    exit 1
  fi

  printf "%b✔ Everything looks fine%b\n" "${GREEN}" "${RESET}"
  exit 0
}

main "${@:-}"
