#!/usr/bin/env bash

GITHUB_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

github_compare_version() {
  source "${GITHUB_SCRIPT_DIR}/meta" && meta_init "var"
  var_color

  if [[ "${#}" -lt 2 ]]; then
    printf "%bUsage: github_compare_version owner/repo latest_version [current_version] [release_api_output_file]%b\n" "${RED}" "${RESET}"
    return 1
  fi

  if [[ -z ${3} ]]; then
    printf "%s" "${2}"
    rm "${4}"
    return
  fi

  if [[ ${3} == "${2}" ]]; then
    printf "%b✔ %s is up to date %s%b\n" "${GREEN}" "${1}" "${2}" "${RESET}"
    rm "${4}"
    return
  fi

  local RELEASE_NOTES
  RELEASE_NOTES="$(python -c "import json; print(json.load(open('${4}'))['body'])")"
  rm "${4}"

  printf "%bNew version for %b%s%b is %b%s%b %s%b\n" "${BLUE}" "${YELLOW}" "${1}" "${BLUE}" "${GREEN}" "${2}" "${BLUE}" "https://github.com/${1}/releases/tag/${2}" "${RESET}"
  printf "%s\n" "${RELEASE_NOTES}"
}

# Slower but works with private
github_last_release_private() {
  source "${GITHUB_SCRIPT_DIR}/meta" && meta_init "var"
  var_color

  if [[ "${#}" -lt 1 ]]; then
    printf "%bUsage: github_last_release_private owner/repo%b\n" "${RED}" "${RESET}"
    return 1
  fi

  var_read GITHUB_OAUTH_TOKEN "" "secret"

  local HTTP_OUTPUT="http_output.txt"

  local HTTP_STATUS
  HTTP_STATUS="$(curl -q -sS -o "${HTTP_OUTPUT}" -w "%{http_code}" -H "Authorization: token ${GITHUB_OAUTH_TOKEN}" "https://api.github.com/repos/${1}/releases/latest")"
  if [[ "${HTTP_STATUS}" != "200" ]]; then
    printf "%bUnable to list latest release for %s%b\n" "${RED}" "${1}" "${RESET}"
    cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
    return
  fi

  github_compare_version "${1}" "$(python -c "import json; print(json.load(open('${HTTP_OUTPUT}'))['tag_name'])")" "${2:-}" "${HTTP_OUTPUT}"
}

github_last_release() {
  source "${GITHUB_SCRIPT_DIR}/meta" && meta_init "var"
  var_color

  if [[ ${#} -lt 1 ]]; then
    printf "%bUsage: github_last_release owner/repo [previous_version] %b\n" "${RED}" "${RESET}"
    return 1
  fi

  local HTTP_OUTPUT="http_output.txt"
  local CLIENT_ARGS=("curl" "-q" "-sSL" "--max-time" "10" "-o" "${HTTP_OUTPUT}" "-w" "%{http_code}")

  local HTTP_STATUS
  HTTP_STATUS="$("${CLIENT_ARGS[@]}" "https://api.github.com/repos/${1}/releases/latest")"
  if [[ ${HTTP_STATUS} != "200" ]]; then
    printf "%bUnable to list latest release for %s%b\n" "${RED}" "${1}" "${RESET}"
    cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
    return
  fi

  github_compare_version "${1}" "$(python -c "import json; print(json.load(open('${HTTP_OUTPUT}'))['tag_name'])")" "${2:-}" "${HTTP_OUTPUT}"
}

github_configure() {
  source "${GITHUB_SCRIPT_DIR}/meta" && meta_init "var"
  var_color

  if [[ ${#} -ne 1 ]]; then
    printf "%bUsage: configure_repository owner/repo%b\n" "${RED}" "${RESET}"
    return 1
  fi

  local HTTP_OUTPUT="http_output.txt"
  local CLIENT_ARGS=("curl" "-q" "-sSL" "--max-time" "10" "-o" "${HTTP_OUTPUT}" "-w" "%{http_code}" "-H" "Authorization: token ${GITHUB_OAUTH_TOKEN}")

  local HTTP_STATUS
  HTTP_STATUS="$("${CLIENT_ARGS[@]}" "-H" "Content-Type: application/json" "-X" "PATCH" "https://api.github.com/repos/${1}" "-d" '{
    "default_branch": "master",
    "allow_merge_commit": false,
    "allow_squash_merge": false,
    "allow_rebase_merge": true,
    "has_wiki": false,
    "has_projects": false
  }')"
  if [[ ${HTTP_STATUS} != "200" ]]; then
    printf "%bUnable to edit ${1}%b\n" "${RED}" "${RESET}"
    cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
    return
  fi

  HTTP_STATUS="$("${CLIENT_ARGS[@]}" "-H" "Accept: application/vnd.github.dorian-preview+json" "-X" "PUT" "https://api.github.com/repos/${1}/vulnerability-alerts")"
  if [[ ${HTTP_STATUS} != "204" ]]; then
    printf "%bUnable to enable vulnerability alerts for ${1}%b\n" "${RED}" "${RESET}"
    cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
    return
  fi

  HTTP_STATUS="$("${CLIENT_ARGS[@]}" "-H" "Accept: application/vnd.github.london-preview+json" "-X" "PUT" "https://api.github.com/repos/${1}/automated-security-fixes")"
  if [[ ${HTTP_STATUS} != "204" ]]; then
    printf "%bUnable to enable automated security fixes for ${1}%b\n" "${RED}" "${RESET}"
    cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
    return
  fi

  rm "${HTTP_OUTPUT}"
}
