#!/usr/bin/env bash

golang_go() {
  if [[ ${BUILD_WITH_DOCKER:-} == "true" ]]; then
    docker run --rm \
      --workdir /go/src/app \
      --volume "$(pwd):/go/src/app" \
      --env GOOS="${GOOS:-linux}" \
      --env GOARCH="${GOARCH:-amd64}" \
      --env CGO_ENABLED="${CGO_ENABLED:-1}" \
      golang:1.15 go "${@}"
  else
    go "${@}"
  fi
}
