#!/usr/bin/env bash

golang_go() {
  if [[ ${BUILD_WITH_DOCKER:-} == "true" ]]; then
    docker run --rm \
      -w /go/src/app \
      -v "$(pwd):/go/src/app" \
      -e GOOS="${GOOS:-linux}" \
      -e GOARCH="${GOARCH:-amd64}" \
      -e CGO_ENABLED="${CGO_ENABLED:-1}" \
      golang:1.14 go "${@:-}"
  else
    go "${@:-}"
  fi
}
