#!/usr/bin/env bash

GPG_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

gpg_config() {
  mkdir -p "${HOME}/.gnupg"
  chmod 700 "${HOME}/.gnupg"

  echo "personal-cipher-preferences AES256 AES192 AES CAST5
personal-digest-preferences SHA512 SHA384 SHA256 SHA224
default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
cert-digest-algo SHA512
s2k-digest-algo SHA512
s2k-cipher-algo AES256
charset utf-8
fixed-list-mode
no-comments
no-emit-version
keyid-format 0xlong
list-options show-uid-validity
verify-options show-uid-validity
with-fingerprint
require-cross-certification" >"${HOME}/.gnupg/gpg.conf"

  gpg --version

  if command -v gpg2 /dev/null 2>&1; then
    gpg2 --version
  fi
}

gpg_import() {
  if [[ $(type -t "var_color") != "function" ]]; then
    source "${GPG_SCRIPT_DIR}/meta" && meta_init "var"
    var_color
  fi

  if [[ ${#} -ne 1 ]]; then
    var_red "Usage: gpg_import GPG_SIGNING_KEY"
    return 1
  fi

  printf "%s" "${1}" | gpg --no-tty --batch --yes --import
}
