#!/usr/bin/env bash

HTTP_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

http_handle_error() {
  source "${HTTP_SCRIPT_DIR}/meta" && meta_init "var"
  var_color

  var_error "HTTP/${HTTP_STATUS}: ${1:-}"
  cat "${HTTP_OUTPUT}" 1>&2 && rm "${HTTP_OUTPUT}"
}

http_init_client() {
  export HTTP_OUTPUT="http_output.txt"
  export HTTP_CLIENT_ARGS=("curl" "-q" "-sSL" "--max-time" "10" "-o" "${HTTP_OUTPUT}" "-w" "%{http_code}" "${@:-}")
  export HTTP_STATUS
}

http_request() {
  HTTP_STATUS="$("${HTTP_CLIENT_ARGS[@]}" "${@:-}")"
}
