#!/usr/bin/env bash

META_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

meta_download_script() {
  if [[ ${#} -ne 1 ]]; then
    printf "Usage: meta_download_script DEPENDENCIE_FILENAME\n"
    return 1
  fi

  local DEPENDENCIE_FILENAME="${1}"
  shift

  printf 1>&2 "Downloading script %s...\n" "${DEPENDENCIE_FILENAME}"

  mkdir -p "$(dirname "${DEPENDENCIE_FILENAME}")"
  curl --disable --silent --show-error --location --max-time 30 -o "${DEPENDENCIE_FILENAME}" -- "${REMOTE_DEPENDENCIES_URL}/${DEPENDENCIE_FILENAME}"
  chmod +x "${DEPENDENCIE_FILENAME}"
}

meta_init() {
  local REMOTE_DEPENDENCIES_URL="https://raw.githubusercontent.com/ViBiOh/scripts/master/"

  cd "${META_SCRIPT_DIR}" || return 1

  for dep in "${@}"; do
    if [[ -z ${dep:-} ]]; then
      continue
    fi

    if ! [[ -e "./${dep}" ]]; then
      meta_download_script "${dep}"
    fi

    if [[ $(grep -c "main()" "./${dep}") -eq 0 ]]; then
      source "./${dep}"
    fi
  done

  cd - >/dev/null || return 1
}
