#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

meta_download_script() {
  1>&2 printf "Download %s\n" "${dep}"

  mkdir -p "$(dirname "${1}")"
  curl -q -sSL --max-time 10 -o "${1}" "${REMOTE_DEPENDENCIES_URL}/${1}"
  chmod +x "${1}"
}

meta_init() {
  local REMOTE_DEPENDENCIES_URL="https://raw.githubusercontent.com/ViBiOh/scripts/master/"

  cd "${SCRIPT_DIR}" || return 1

  for dep in "${@}"; do
    if ! [[ -e "./${dep}" ]]; then
      meta_download_script "${dep}"
    fi

    if [[ "$(grep -c "main()" "./${dep}")" -eq 0 ]]; then
      source "./${dep}"
    fi
  done

  cd - > /dev/null || return 1
}
