#!/usr/bin/env bash

_pass_scripts_init() {
  return 0
}

pass_get() {
  if ! command -v pass >/dev/null 2>&1; then
    return
  fi

  if [[ ${#} -lt 2 ]]; then
    var_red "Usage: passget PASS_NAME PASS_FIELD"
    return 1
  fi

  local PASS_NAME="${1}"
  shift

  if ! [[ -e "${PASSWORD_STORE_DIR:-${HOME}/.password-store}/${PASS_NAME}.gpg" ]]; then
    return
  fi

  local PASS_FIELD="${1}"
  shift

  pass show "${PASS_NAME}" | awk -v "field=${PASS_FIELD}" -F': ' '$1 == field {printf("%s", $2)}'
}
