#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

main() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  source "${SCRIPT_DIR}/meta" && meta_init "var"
  var_color

  local CURRENT_NAME=""
  local CURRENT_COUNT=0
  local CURRENT_REGEX='([a-zA-Z0-9]*)_backup_.*'

  while IFS= read -r -d '' file; do
    if [[ ${file} =~ ${CURRENT_REGEX} ]]; then
      if [[ ${CURRENT_NAME} == "${BASH_REMATCH[1]}" ]]; then
        CURRENT_COUNT=$((CURRENT_COUNT + 1))
      else
        CURRENT_NAME="${BASH_REMATCH[1]}"
        CURRENT_COUNT=1
      fi

      if [[ ${CURRENT_COUNT} -gt 5 ]]; then
        rm "${file}"
        var_success "File ${file} deleted!"
      fi
    fi
  done < <(find . -type f -name '*' -print0 | sort --zero-terminated --reverse)
}

main "${@}"
