#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

main() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  source "${SCRIPT_DIR}/meta" && meta_init "var"
  var_color

  var_read SLACK_LEGACY_TOKEN "" "secret"
  var_read SLACK_USER

  local UNTIL_DATE
  UNTIL_DATE="$(date -d "${1:-6 month ago}" +%Y%m%d)"

  local CLEANER_ARGS=("docker" "run" "-it" "--rm" "sgratzl/slack-cleaner" "-c")

  printf "%bCleanning all messages and files until %s%b\n" "${BLUE}" "${UNTIL_DATE}" "${RESET}"

  local TARGETS=('channel' 'group' 'direct')
  local TYPES=('message' 'file')

  for target in ${TARGETS[@]}; do
    for type in ${TYPES[@]}; do
      ${CLEANER_ARGS[@]} "slack-cleaner --token ${SLACK_LEGACY_TOKEN} --user ${SLACK_USER} --rate 1 --perform --${type} --regex --${target} '.*' --keeppinned --before ${UNTIL_DATE}"
    done
  done
}

main "${@:-}"
