#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

main() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  source "${SCRIPT_DIR}/meta" && meta_init "var"
  var_color

  local DEFAULT_UNTIL_DATE
  DEFAULT_UNTIL_DATE="$(date -d "${1:-3 month ago}" +%Y%m%d)"

  var_read SLACK_LEGACY_TOKEN "" "secret"
  var_read SLACK_USER
  var_read UNTIL_DATE "${DEFAULT_UNTIL_DATE}"

  local TARGETS=("${2:-channel group direct}")
  local TYPES=("${3:-message file}")

  local CLEANER_ARGS=("docker" "run" "-it" "--rm" "sgratzl/slack-cleaner" "-c")

  printf "%bCleanning all messages and files until %s%b\n" "${BLUE}" "${UNTIL_DATE}" "${RESET}"

  for target in ${TARGETS[@]}; do
    for type in ${TYPES[@]}; do
      ${CLEANER_ARGS[@]} "slack-cleaner --token ${SLACK_LEGACY_TOKEN} --user ${SLACK_USER} --rate 1 --perform --${type} --regex --${target} '.*' --before ${UNTIL_DATE}"
    done
  done
}

main "${@:-}"
