#!/usr/bin/env bash

var_read() {
  if [[ ${#} -lt 1 ]]; then
    var_error "Usage: var_read VAR_NAME [VAR_DEFAULT] [VAR_SECRET]"
    return 1
  fi

  local VAR_NAME="${1}"
  shift
  local VAR_DEFAULT="${1:-}"
  shift || true
  local VAR_SECRET="${1:-}"
  shift || true

  local SECRET_ARG=""
  if [[ ${VAR_SECRET:-} == "secret" ]]; then
    SECRET_ARG="-s"
  fi

  if [[ -z ${!VAR_NAME:-} ]]; then
    if [[ -z ${SCRIPTS_NO_INTERACTIVE:-} ]]; then
      read ${SECRET_ARG?} -r -p "${VAR_NAME}${VAR_DEFAULT:+ [${VAR_DEFAULT}]}=" READ_VALUE
    fi

    eval "${VAR_NAME}=${READ_VALUE:-${VAR_DEFAULT}}"

    if [[ ${SECRET_ARG} == "-s" ]]; then
      printf "\n" 1>&2
    fi
  elif [[ ${SECRET_ARG} != "-s" ]]; then
    printf "%s=%s\n" "${VAR_NAME}" "${!VAR_NAME}" 1>&2
  else
    printf "Using secret %s\n" "${VAR_NAME}" 1>&2
  fi
}

var_confirm() {
  local VAR_CONFIRM_MESSAGE="${1:-Are you sure}"

  read -r -p "${VAR_CONFIRM_MESSAGE}? [Y/n] " input

  case "${input}" in
  [yY][eE][sS] | [yY])
    return 0
    ;;

  *)
    return 1
    ;;
  esac
}

var_color() {
  export RED='\033[0;31m'
  export GREEN='\033[0;32m'
  export BLUE='\033[0;34m'
  export YELLOW='\033[33m'
  export RESET='\033[0m'
}

var_log() {
  local COLOR="${1}"
  shift

  printf "%b%b %b\n" "${COLOR}" "${@}" "${RESET}" 1>&2
}

var_error() {
  var_log "${RED}" "${@}"
}

var_warning() {
  var_log "${YELLOW}" "${@}"
}

var_success() {
  var_log "${GREEN}" "${@}"
}

var_info() {
  var_log "${BLUE}" "${@}"
}
