#!/usr/bin/env bash

var_read() {
  local SECRET_ARG=""
  if [[ ${3:-} == "secret" ]]; then
    SECRET_ARG="-s"
  fi

  if [[ -z ${!1:-} ]]; then
    if [[ -z ${SCRIPTS_NO_INTERACTIVE:-} ]]; then
      read ${SECRET_ARG?} -r -p "${1}${2:+ [${2}]}=" READ_VALUE
    fi

    eval "${1}=${READ_VALUE:-${2}}"

    if [[ ${SECRET_ARG} == "-s" ]]; then
      printf "\n" 1>&2
    fi
  elif [[ ${SECRET_ARG} != "-s" ]]; then
    printf "%s=%s\n" "${1}" "${!1}" 1>&2
  else
    printf "Using secret %s\n" "${1}" 1>&2
  fi
}

var_confirm() {
  read -r -p "${1:-Are you sure}? [Y/n] " input

  case "${input}" in
  [yY][eE][sS] | [yY])
    printf "true"
    ;;

  *)
    printf "false"
    ;;
  esac
}

var_color() {
  export RED='\033[0;31m'
  export GREEN='\033[0;32m'
  export BLUE='\033[0;34m'
  export YELLOW='\033[33m'
  export RESET='\033[0m'
}

var_error() {
  printf "%b%b%b\n" "${RED}" "${1:-}" "${RESET}" 1>&2
}

var_warning() {
  printf "%b%b%b\n" "${YELLOW}" "${1:-}" "${RESET}" 1>&2
}

var_success() {
  printf "%b%b%b\n" "${GREEN}" "${1:-}" "${RESET}" 1>&2
}

var_info() {
  printf "%b%b%b\n" "${BLUE}" "${1:-}" "${RESET}" 1>&2
}
