#!/usr/bin/env bash

set -o nounset -o pipefail

if [[ ${TRACE:-0} == "1" ]]; then
  set -o xtrace
fi

main() {
  meta_check "var" "git"

  local FIRST_LINE
  FIRST_LINE="$(head -1 "${1}")"

  if git_is_commit_wip "${FIRST_LINE}"; then
    exit 0
  fi

  if ! git_is_conventional_commit "${FIRST_LINE}"; then
    git_conventionnal_commit_guidelines
    exit 1
  fi

  if ! git_is_valid_description "${FIRST_LINE}"; then
    git_valid_description_guideline "${FIRST_LINE}"

    if ! var_confirm "Do you want to override"; then
      exit 1
    fi
  fi

  exit 0
}

main "${@}"
