#!/usr/bin/env bash

set -o nounset -o pipefail

sed_inplace() {
  if [[ ${OSTYPE} =~ ^darwin ]]; then
    sed -i '' "${@}"
  else
    sed -i "${@}"
  fi
}

main() {
  local BRANCH_NAME
  BRANCH_NAME=$(git symbolic-ref --short HEAD)

  local FIRST_LINE
  FIRST_LINE="$(head -1 "${1}")"

  if [[ ! ${FIRST_LINE} =~ ^fixup! ]] && [[ -n ${BRANCH_NAME} && ${BRANCH_NAME} =~ (features|fixes)/([A-Z0-9]+[-_][0-9]+) ]]; then
    local PREFIX="${BASH_REMATCH[2]}"

    if [[ ! ${FIRST_LINE} =~ ^${PREFIX} ]]; then
      sed_inplace -e "1s|^|${PREFIX} |" "${1}"
    fi
  fi

  exit 0
}

main "${@:-}"
