#!/usr/bin/env bash

set -o nounset -o pipefail

script_dir() {
  if [[ -L ${BASH_SOURCE[0]} ]]; then
    dirname "$(readlink "${BASH_SOURCE[0]}")"
  else
    (
      cd "$(dirname "${BASH_SOURCE[0]}")" && pwd
    )
  fi
}

main() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(script_dir)"

  source "${SCRIPT_DIR}/../meta" && meta_init "git"
  git_conventionnal_commits

  local BRANCH_NAME
  BRANCH_NAME=$(git branch --show-current)

  local FIRST_LINE
  FIRST_LINE="$(head -1 "${1}")"

  if git_is_commit_wip "${FIRST_LINE}"; then
    exit 0
  fi

  if [[ -n ${BRANCH_NAME} && ${BRANCH_NAME} =~ (features/|fixes/|feat-|fix-)?([A-Z0-9]+[-_][0-9]+) ]]; then
    local PREFIX="${BASH_REMATCH[2]}"

    if [[ ! ${FIRST_LINE} =~ ${PREFIX} ]]; then
      if git_is_conventional_commit "${FIRST_LINE}"; then
        perl -pi'' -e "s|^(revert:\ )?($(printf "%s\|" "${!CONVENTIONAL_COMMIT_SCOPES[@]}"))(\(.+\))?(\!?):|\1\2\3\4: ${PREFIX}|" "${1}"
      else
        perl -pi'' -e "s|^|${PREFIX} |" "${1}"
      fi
    fi
  fi

  exit 0
}

main "${@}"
