---

name: Automerge
on:
  check_suite:
    types: [completed]
jobs:
  build:
    name: Automerge
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
        run: |
          if [[ "${{ github.event.check_suite.conclusion }}" -eq "success" ]]; then
            curl -q -sSL "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "github_merge"

            for pr in ${{ github.event.check_suite.pull_requests }}; do
              scripts/github_merge "${{ github.token }}" "${{ github.repository }}" "$(echo "${pr}" | jq '.number')"
            done
          fi
